site_name: Yudong's Notes

theme:
  name: material
  font: false
  features:
    - navigation.instant
    - navigation.instant.progress

plugins:
  - search

# 让 Markdown 识别 $...$ / $$...$$
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
  - javascripts/katex.js

nav:
  - Home: index.md
  - NLP:
      - 自然语言处理概要: 自然语言处理初始步骤.md
      - 信息检索问题: 信息检索问题.md
