site_name: Yudong's Notes
theme:
  name: material
plugins:
  - search

# 新增：让 Markdown 识别 $...$ / $$...$$
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# 新增：加载 MathJax（以及一个本地初始化脚本）
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - NLP:
      - 自然语言处理概要: 自然语言处理初始步骤.md
      - 信息检索问题: 信息检索问题.md

